import Link from 'next/link';
import type {Snapshot} from '@/lib/types';
import {summarize} from '@/lib/summary';
import {money} from '@/lib/format';
import MonthPicker from './MonthPicker';
export default function Dashboard({data,month}:{data:Snapshot;month:string}){
 const {rows,totals}=summarize(data);const pending=data.expenses.filter(e=>e.status==='committed');
 const monthLabel=new Date(month+'T12:00:00Z').toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'});
 const status=(r:{remaining:number;usage:number})=>r.remaining<0?'over':r.usage>=80?'watch':'healthy';
 return <><header className="page-heading"><div><p className="eyebrow">YOUR MONTH, AT A GLANCE</p><h1>Budget overview</h1><p className="muted">A clear picture of where your marketing budget stands.</p></div><MonthPicker month={month}/></header>
 <div className="summary-cards">{[['Approved budget',totals.approved,'Monthly spending limit','approved-card'],['Committed',totals.committed,`${pending.length} expenses awaiting approval`,'committed-card'],['Actual spend',totals.actual,'Approved expenses','actual-card'],['Remaining budget',totals.remaining,'After actual + committed','remaining-card']].map(([label,value,caption,style])=><section key={label as string} className={`summary-card ${style}`}><p>{label}</p><strong>{money(value as number)}</strong><small>{caption}</small></section>)}</div>
 {!data.budgets.length&&<div className="setup-banner"><div><strong>No budgets set for {monthLabel}</strong><p>Set a monthly limit to see how much room you have left. Any expenses below still count toward spend.</p></div><Link className="button" href={`/budgets?month=${month.slice(0,7)}`}>Set budget →</Link></div>}
 <section className="panel"><div className="panel-heading"><div><h2>Budget by category</h2><small>{monthLabel} · Committed and actual spend shown separately</small></div><Link href={`/budgets?month=${month.slice(0,7)}`}>Manage budgets ↗</Link></div>{!rows.length?<div className="empty"><h3>Start with your first category</h3><p>Organize spend, set a budget, then log an expense.</p><Link className="button" href="/categories">Add category</Link></div>:<div className="table-scroll"><table className="budget-table"><thead><tr><th>Category</th><th className="numeric">Approved</th><th className="numeric">Committed</th><th className="numeric">Actual</th><th className="numeric">Remaining</th><th>Budget used</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong>{!r.hasBudget&&<small>No budget set</small>}</td><td className="numeric">{money(r.approved)}</td><td className="numeric">{money(r.committed)}</td><td className="numeric">{money(r.actual)}</td><td className={`numeric balance ${status(r)}`}>{money(r.remaining)}</td><td><div className="usage"><div className="track"><span className={status(r)} style={{width:`${Math.min(100,r.usage)}%`}}/></div><span>{r.usage}%</span></div><small className={status(r)}>{r.remaining<0?'Over budget':!r.hasBudget?'Unbudgeted':r.usage>=80?'Near limit':'On track'}</small></td></tr>)}</tbody><tfoot><tr><td>Total</td><td className="numeric">{money(totals.approved)}</td><td className="numeric">{money(totals.committed)}</td><td className="numeric">{money(totals.actual)}</td><td className={`numeric ${totals.remaining<0?'over':'healthy'}`}>{money(totals.remaining)}</td><td/></tr></tfoot></table></div>}<div className="panel-note">Remaining = approved budget − actual spend − committed expenses.</div></section>
 <div className="dashboard-bottom"><section className="panel"><div className="panel-heading"><h2>Recent expenses</h2><Link href={`/expenses?month=${month.slice(0,7)}`}>View all ↗</Link></div>{!data.expenses.length?<div className="empty"><p>No expenses yet for this month.</p><Link className="button secondary" href={`/expenses?month=${month.slice(0,7)}`}>Add expense</Link></div>:data.expenses.slice(0,5).map(e=><Link className="recent-row" key={e.id} href={`/expenses/${e.id}`}><div className="vendor-icon">{e.vendor.slice(0,1).toUpperCase()}</div><div className="recent-description"><strong>{e.vendor}</strong><small>{e.expense_date} · {data.categories.find(c=>c.id===e.category_id)?.name}</small></div><div className="recent-value"><strong>{money(Number(e.amount))}</strong><small><span className={`badge ${e.status}`}>{e.status==='actual'?'Actual':'Committed'}</span></small></div><span>↗</span></Link>)}</section><section className="review-card"><span className="review-icon">↗</span><p className="eyebrow">KEEP THINGS MOVING</p><h2>{pending.length?`${pending.length} expenses need a review`:'You’re all caught up'}</h2><p>{pending.length?`${money(totals.committed)} is committed and awaiting approval. Review the details before moving it to actual spend.`:'There are no pending approvals for this month. New expenses will appear here when your team logs them.'}</p><Link className="button" href={`/expenses?month=${month.slice(0,7)}`}>{pending.length?'Review expenses':'Log an expense'} →</Link><small>Approval moves spend from committed to actual; your remaining budget stays the same.</small></section></div>
 </>;
}
